In [5]:
import torch

x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print(x*y)

tensor([10.,  3.])


In [6]:
x = torch.zeros([2,5])
print(x)


tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [7]:
x. shape

torch.Size([2, 5])

In [13]:
y = torch.rand([2,5])
print(y)

tensor([[0.4917, 0.4344, 0.3712, 0.4245, 0.0220],
        [0.2623, 0.9145, 0.5413, 0.4081, 0.2857]])


In [14]:
#Flatting an image is making an array x by y to 1 by x*y
y = y.view([1,10])
print(y)

tensor([[0.4917, 0.4344, 0.3712, 0.4245, 0.0220, 0.2623, 0.9145, 0.5413, 0.4081,
         0.2857]])
